### ISSUE TITLE
Not sure how to do a PR, but I have a fix

### ISSUE THREAD

**Issue by fowlis** [x6r/dracula#16]
```css
.container-2wlB3z{background-color:var(--dracula-primary)}
```
fixes the area below the member list not having the same background colour as above - it's only really noticeable on small servers
(not sure if this happens on the other discord mod clients, but I found this on BetterDiscord)   

Before:
![Screenshot_7](https://user-images.githubusercontent.com/84232621/148069786-a505ba55-44cf-4461-a8a2-cfe48ebf9cae.png)
After:
![Screenshot_8](https://user-images.githubusercontent.com/84232621/148069797-647fe655-dc9b-4a38-8119-9c96324f0ee9.png)
